### PR TITLE
Switch to Ruff

### PR DESCRIPTION
**Pull request by tuomas777**
Similar to [what is done to Linked Events](https://github.com/City-of-Helsinki/linkedevents/pull/1005). Has the same lint rules and configuration with one minor tweak: `N802` is ignored for tests, because they seem to have convention of uppercasing HTTP method names in function names.

Safe automatic commits https://github.com/City-of-Helsinki/kerrokantasi/pull/522/commits/78b6d3d506987834917b9bdb765f59b4dc7ebdb1, https://github.com/City-of-Helsinki/kerrokantasi/pull/522/commits/21aeb0d8704e7601dd0379d3e40a1a52b2b2bad8 and https://github.com/City-of-Helsinki/kerrokantasi/pull/522/commits/144f0a1a0f127f82987350a9ffd2057e06b468f7 don't need a manual review.

Also removed some obsolete code in this PR instead of reformatting it.

Refs [KER-395](https://helsinkisolutionoffice.atlassian.net/browse/KER-395)

[KER-395]: https://helsinkisolutionoffice.atlassian.net/browse/KER-395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**KERROKANTASI-API branch is deployed to platta: https://kerrokantasi-pr522.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**KERROKANTASI-API branch is deployed to platta: https://kerrokantasi-pr522.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**KERROKANTASI-API branch is deployed to platta: https://kerrokantasi-pr522.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**KERROKANTASI-API branch is deployed to platta: https://kerrokantasi-pr522.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**KERROKANTASI-API branch is deployed to platta: https://kerrokantasi-pr522.api.dev.hel.ninja** :rocket::rocket::rocket:

**Review by danipran — APPROVED** [review]
LGTM! 👍

**Comment by terovirtanen** [comment]
**KERROKANTASI-API branch is deployed to platta: https://kerrokantasi-pr522.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**KERROKANTASI-API branch is deployed to platta: https://kerrokantasi-pr522.api.dev.hel.ninja** :rocket::rocket::rocket:

**Pull request merged**
