### PR TITLE
deps: upgrade django to 4.2

### PR DESCRIPTION
**Pull request by nicobav**
And bump all applicable dependencies as well.

Refs KER-342

### CODE REVIEW

**Comment by terovirtanen** [comment]
**KERROKANTASI-API branch is deployed to platta: https://kerrokantasi-pr491.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**KERROKANTASI-API branch is deployed to platta: https://kerrokantasi-pr491.api.dev.hel.ninja** :rocket::rocket::rocket:

**Review by danipran — APPROVED** [review]
Seems to work, tried out the PR environment with Django Admin and local UI. Tried creating, editing, copying and deleting hearings.

Not sure what Snyk is complaining about.

**Comment by terovirtanen** [comment]
**KERROKANTASI-API branch is deployed to platta: https://kerrokantasi-pr491.api.dev.hel.ninja** :rocket::rocket::rocket:

**Pull request merged**
