### PR TITLE
PostGIS geometry for queries + tests

### LINKED ISSUE #255: Transition geojson to proper PostGIS
This will allow bbox-filtering of hearings and comments

### PR DESCRIPTION
**Pull request by indigane**
Resolves #255

### CODE REVIEW

**Comment by indigane** [comment]
This needs pull req #274 and postgis configuration for travis

**Comment by Rikuoja** [comment]
Oh beautiful. I fixed the issue in master, so the PR should work now, but apparently you'll have to rebase this to the current master and create a new PR for the tests to succeed. Currently, travis tries to run the PR tests on the commit rebased on the old master head, which doesn't support postgis.

Tl;dr: rebase to master and reopen PR to get travis up to date.

**Comment by Rikuoja** [comment]
Okay, I guess I can reopen it and just wait for rebase. Will finally rerun the tests then.

**Comment by Rikuoja** [comment]
Oh beautiful, the nightly build still fails for unknown reason, so switched master to 3.7-dev. Let's hope rebasing to it will fix the test problem, as the problem is completely unrelated to this branch.

**Pull request merged**
