### PR TITLE
Add upload endpoint v1/file to allow file uploads linked to a section

### LINKED ISSUE #266: Add upload endpoint v1/file to allow file uploads linked to a section
- [x] Also, add `files` array to the section json (similar to the `images` array) that will list files belonging to a section.

- [ ] For listing the `/v1/file` endpoint, refactor/generalize the https://github.com/City-of-Helsinki/kerrokantasi/blob/master/democracy/views/section.py#L182 `ImageViewSet` so that the same code is used for both `/v1/file` and `/v1/image` endpoints.

- [x] Similarly, add tests for file endpoint and section file listing (similar to existing tests for images) to ascertain that only files belonging to *published* sections are listed.

- [x] Files do exist on the server `media` directory already, uploaded via django-admin, but not exposed at any endpoint. The server should only allow fetching the file if it the hearing is public and the file is listed on the file endpoint; we should use e.g. https://github.com/johnsensible/django-sendfile for that.

- [x] Make a migration to scan existing hearing section HTML for references to existing uploaded files and add them to the database accordingly.

### PR DESCRIPTION
**Pull request by jussih**
Resolves #266 

When releasing, django-sendfile settings will need to be configured on the server:
```
SENDFILE_BACKEND = 'sendfile.backends.nginx'
```
Sendfile is configured so that the path `os.path.join(BASE_DIR, "var", "protected")` and the url `/protected` must be protected in nginx configuration with the sendfile-functionality. See https://github.com/johnsensible/django-sendfile#nginx-backend

The change introduced it quite a big one, changing existing data (the ckeditor uploaded files and their urls). The implementation contains automatic tests and has been tested in a local development environment, but this should be tested in staging thoroughly before taking into production.

* Configure NGINX
* Run the conversion script as dry run, using the correct domain (in local development this would be ` --domain=http://localhost:8000` and in production `--domain=https://api.hel.fi/kerrokantasi`) `python manage.py convert_ckeditor_uploads --dry --domain=https://staging-server.fi/kerrokantasi`
* Check the output looks ok. It should list sections and moving & renaming files. Snippet of example output:
```
Section [39/210]
Section [40/210]
* Moved /home/heikkjus/code/helsinki/kerrokantasi/media/uploads/2018/10/16/test_07OVR52.zip to /home/heikkjus/code/helsinki/kerrokantasi/var/protected/2018/10/test_07OVR52.zip
* fi: Rewrote URL http://localhost:8000/media/uploads/2018/10/16/test_07OVR52.zip -> http://localhost:8000/v1/download/sectionfile/12/
Section [41/210]
```
* If everything seems fine, run it again, this time without `--dry`, so files are actually moved.
* Verify you can still access files of open hearings in an incognito browser. The urls should now look like `http://localhost:8000/v1/download/sectionfile/12/`
* Close the hearing in admin. Verify in the incognito browser the file now produces 404 response.
* In admin, upload a new file using the ckeditor link tool. Save the hearing. Check in an incognito browser the file opens correctly.

What has been implemented:
- File upload endpoint `/v1/file/` accepting form/multipart POST requests with file metadata and uploaded file
- Translated metadata (title and caption) must be represented as a string containing valid json, see curl example below
- Section id can be left out when uploading a file. Afterwards a user with admin in ANY organization can attach the file to a section using a PUT request to the file detail endpoint. The user has to be an admin in the organization which contains the section the file will be attached to.
- `/v1/file/` endpoint lists metadata of all files belonging to hearings the current user can see, AND orphaned files (not attached to any section) IF the user is admin in any organization.
- `url` attribute of a file contains the sendfile-protected download url which can be used to access the file contents if the current user has access to that file.
- CKeditor file upload endpoint changed to put files into the sendfile-protected directory and generate the appropriate URL for downloading the file
- Management command `convert_ckeditor_uploads`: Parses all the section contents for files uploaded using ckeditor link tool, moves the files to the sendfile-protected directory, adds the file data to the database and `file` endpoint. Rewrites the links in the content to point to the protected URL.

CURL example for uploading a new file:
```
curl -X POST \
  http://localhost:8000/v1/file/ \
  -H 'accept: application/json' \
  -H 'authorization: JWT [valid jwt token]' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
  -F uploaded_file=@mona_lisa.png \
  -F section=nREpeKghqsGMFGpV5hVaVTVjgviu0lAb \
  -F 'title={"en": "File title", "fi": "Tiedoston otsikko"}' \
  -F 'caption={"en": "File caption", "fi": "Tiedoston kuvaus"}'
```
Images are not handled via sendfile at this point.

### CODE REVIEW

**Comment by Rikuoja** [comment]
As regards the file uploads, actually the ckeditor has lots of files uploaded.

They have been uploaded using the ckeditor link tool, which contains the option to upload a file instead of linking to an existing file. It has been used quite profusely in the past.

**Comment by Rikuoja** [comment]
But as regards the images uploaded with ckeditor, they indeed should be found in the image endpoint, and only the other attachments in the file endpoint.

**Comment by Rikuoja** [comment]
I'm afraid that we do want to treat images the same way eventually (with sendfile), but we may create a separate PR later for the images.

**Comment by jussih** [comment]
Ok, data migration should be created next with the following specifications:
- Parse the ckeditor content for images uploaded using ckeditor image tool, add the image data to the database and `image` endpoint.
- Change the `` tags in ckeditor content to point to the corresponding image in the `image` endpoint
- Parse the ckeditor content for files uploaded using ckeditor link tool, add the file data to the database and `file` endpoint.
- Change the links in ckeditor content to point to the corresponding file in the sendfile-protected `download` endpoint.

**Comment by jussih** [comment]
Updated the TODO note.

**Comment by jussih** [comment]
The ckeditor file upload using the link tool causes the following POST request with the file data as payload:

```
curl 'http://localhost:8000/upload/?CKEditor=id_sections-0-content&CKEditorFuncNum=1&langCode=en' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Language: fi,en-US;q=0.7,en;q=0.3' --compressed -H 'Referer: http://localhost:8000/admin/democracy/hearing/zYBqyRbso3cHM3OH8gBPvDQvVV0Mdr3d/change/?language=fi' -H 'Content-Type: multipart/form-data; boundary=---------------------------205494781518594735001354244728' -H 'Cookie: kerrokantasi-csrftoken=[csrftoken removed]; kerrokantasi-sessionid=[sessionid removed]; ckCsrfToken=[csrftoken removed]' -H 'Connection: keep-alive' -H 'Upgrade-Insecure-Requests: 1' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' --data ''
```

The response payload is a javascript snippet 
```
        <script type='text/javascript'>
            window.parent.CKEDITOR.tools.callFunction(1, 'http://localhost:8000/media/uploads/2018/10/16/patch.diff');
        </script>
```

**Pull request merged**
