### PR TITLE
KER-368 | Add audit logging

### PR DESCRIPTION
**Pull request by charn**
This PR adds audit logging machinery which takes inspiration from a few project already implementing audit logging [[1](https://github.com/City-of-Helsinki/atv/), [2](https://github.com/City-of-Helsinki/yjdh/), [3](https://github.com/City-of-Helsinki/apartment-application-service/), [4](https://github.com/City-of-Helsinki/linkedevents/), [5](https://github.com/City-of-Helsinki/open-city-profile/)]. Audit logs are created by `AuditLogMiddleware` based on audit loggable content added to the request.

Initially audit logging is added API views which mutate objects:
- `HearingViewSet`
- `ImageViewSet`
- `LabelViewSet`
- `ContactPersonViewSet`
- `FileViewSet`
- `BaseCommentViewSet`

### CODE REVIEW

**Comment by terovirtanen** [comment]
**KERROKANTASI-API branch is deployed to platta: https://kerrokantasi-pr509.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**KERROKANTASI-API branch is deployed to platta: https://kerrokantasi-pr509.api.dev.hel.ninja** :rocket::rocket::rocket:

**Review by nicobav — APPROVED** [review]
Great to see this giant at the goal line 🎉 

On commit  `refactor: remove reduntant return clauses from perform_create/update` could fix a misspelled `reduntant` to `redundant`.

**Comment by terovirtanen** [comment]
**KERROKANTASI-API branch is deployed to platta: https://kerrokantasi-pr509.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**KERROKANTASI-API branch is deployed to platta: https://kerrokantasi-pr509.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**KERROKANTASI-API branch is deployed to platta: https://kerrokantasi-pr509.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**KERROKANTASI-API branch is deployed to platta: https://kerrokantasi-pr509.api.dev.hel.ninja** :rocket::rocket::rocket:

**Pull request merged**
