### PR TITLE
KER-384 | Upgrade to Python 3.9

### PR DESCRIPTION
**Pull request by nicobav**
- Upgrades to Python 3.9
  - Specify image in arg in Dockerfile to enable use of custom image in different environments. Defaults to docker hub's python:3.9-bookworm.

- Use pre-commit  v9.18.0 (because commintlintrc.js does not work with version 9.13 and below)

Refs KER-384

### CODE REVIEW

**Review by tuomas777 — CHANGES_REQUESTED** [review]
These need to be updated as well

https://github.com/City-of-Helsinki/kerrokantasi/blob/91d363ead1d297fc397ebbcd6b4d94fbf4fedab8/README.md?plain=1#L143
https://github.com/City-of-Helsinki/kerrokantasi/blob/91d363ead1d297fc397ebbcd6b4d94fbf4fedab8/sonar-project.properties#L3

Also, it would be nice to have the Python version change mentioned in the release notes, but chores won't normally end up there. Adding [`Release-As: 1.7.0`](https://github.com/googleapis/release-please?tab=readme-ov-file#how-do-i-change-the-version-number) to the commit message **might** do the trick.

**Comment by terovirtanen** [comment]
**KERROKANTASI-API branch is deployed to platta: https://kerrokantasi-pr520.api.dev.hel.ninja** :rocket::rocket::rocket:

**Review by tuomas777 — APPROVED** [review]
LGTM 👍 🐦

**Comment by tuomas777** [comment]
> Also, it would be nice to have the Python version change mentioned in the release notes, but chores won't normally end up there. Adding [`Release-As: 1.7.0`](https://github.com/googleapis/release-please?tab=readme-ov-file#how-do-i-change-the-version-number) to the commit message **might** do the trick.

It didn't do the trick 😞

**Pull request merged**
